### PR TITLE
Activate the vendd license key if one exists, and check this on a weekly basis

### LINKED ISSUE #275: Do a weekly check to make sure the license key is activated
Since Vendd is a free theme, people sometimes fail to remember to activate their theme, so we'll make that easier on them.

Conditions:
* Already activated copies will not send an activation request
* If the license key field is empty, it will not send an activation request.
* If a license key is not empty, and it is not activated, we will attempt to activate it.
* This should be run on a weekly cron.

### PR DESCRIPTION
**Pull request by cklosowski**
Fixes #275 

Needed for testing:
* WP Crontrol
* A way to directly input a value into the options table
    * Debug Bar console
    * Direct DB Access
* A valid Vendd license key from the live EDD Site. 

To test this:
- [ ] Setup a fresh install with Vendd, and make sure you have no license key entered at `Appearance > Vendd License Key`
- [ ] Use your perfered method to drectily add an option with a name of `vendd_license_key` and option of the license key from the live site.
- [ ] Go to `Appearance > Vendd License Key` and you'll see that your key is present, and the button says `Activate License`
- [ ] In WP Crontrol click `Run Now` on the `edd_weekly_scheduled_events` event.
- [ ] Go back to `Appearance > Vendd License Key` and see that the license has been activated.

### CODE REVIEW

**Comment by mihaijoldis** [comment]
Tested and works as intended!

**Review by ashleyfae — APPROVED** [review]
This works absolutely fine. But IMO it would be a bit more convenient for future maintenance if this code were moved to a separate file.

It looks like `theme-updater-admin.php` is _mostly_ the logic from the SL sample, just renamed and with some adjustments. In the long term it would be nice if we kept custom functionality out of here so we can update the updater code more easily without worrying about losing customizations.

**Comment by cklosowski** [comment]
I can do that @ashleyfae, I'll update it to be in a separate file.

**Comment by cklosowski** [comment]
@ashleyfae Without a complete overhaul of the sample code this isn't easily possible. The problem is that `theme-updater.php` instantiates a new `EDD_Theme_Updater_Admin`, which is what contains the `activate_license` method. However it is just defined in a local variable `$updater` and isn't something we can pass somewhere else without modifying the sample quite a bit.

So any changes to break this out into it's own is going to be a deviation from the sample anyway, since we can't add it to the `theme-updater.php` or use `$updater` anywhere outside of `theme-updater.php` either.

**Comment by cklosowski** [comment]
If we were to just instantiate the updater admin class altogether we'd have to duplicate the entire call including all the config and strings.

**Comment by ashleyfae** [comment]
We can save that for a separate time. I do believe it should eventually be reworked, but we can do that later since it's a bigger project.

**Review by robincornett — APPROVED** [review]

**Pull request merged**
